# Generated by Django 4.2.7 on 2024-06-06 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('número_de_inventario', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('teléfono_encargado', models.CharField(max_length=100)),
                ('descripción', models.TextField(max_length=500)),
                ('ubicación', models.CharField(max_length=100)),
                ('costo_de_adquisición', models.IntegerField()),
                ('fecha_de_adquisición', models.DateField(default=datetime.date.today)),
                ('fecha_de_retirada', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(max_length=100)),
                ('garantía', models.CharField(max_length=100)),
                ('software_instalado', models.CharField(max_length=100)),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('intervalo_mantenimiento', models.IntegerField()),
                ('image', models.ImageField(upload_to='pc/image')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimientoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.time(13, 40, 53, 785071))),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time(13, 40, 53, 785098))),
                ('operador', models.CharField(default='', max_length=100)),
                ('partes_y_piezas', models.TextField(default='', max_length=500)),
                ('descripción', models.TextField(default='', max_length=500)),
                ('image', models.ImageField(default=None, upload_to='pc/mantenimiento/image')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_pc.pc')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_pc.tipomantenimientopc')),
            ],
        ),
    ]
