# Generated by Django 4.2.7 on 2024-04-11 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_pc', '0004_alter_mantenimientopc_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientopc',
            name='descripción',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mantenimientopc',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mantenimientopc',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(1, 22, 44, 126380)),
        ),
        migrations.AddField(
            model_name='mantenimientopc',
            name='image',
            field=models.ImageField(default=None, upload_to='pc/mantenimiento/image'),
        ),
        migrations.AddField(
            model_name='mantenimientopc',
            name='partes_y_piezas',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mantenimientopc',
            name='hora',
            field=models.TimeField(default=datetime.time(1, 22, 44, 126435)),
        ),
    ]
