# Generated by Django 4.2.7 on 2024-04-11 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_pc', '0005_mantenimientopc_descripción_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopc',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 44, 12, 639298)),
        ),
        migrations.AlterField(
            model_name='mantenimientopc',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(18, 44, 12, 639252)),
        ),
    ]
