# Generated by Django 4.2.7 on 2024-04-12 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_pc', '0006_alter_mantenimientopc_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopc',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 3, 40, 484351)),
        ),
        migrations.AlterField(
            model_name='mantenimientopc',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(20, 3, 40, 484319)),
        ),
    ]
