# Generated by Django 4.2.7 on 2024-04-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_repuesto.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_repuesto.partes')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida', models.IntegerField()),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_repuesto.partes')),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosca', models.CharField(blank=True, max_length=50, null=True)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('und', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_repuesto.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.IntegerField()),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_repuesto.partes')),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad_necesaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_repuesto.partes')),
            ],
        ),
    ]
