# Generated by Django 4.2.7 on 2024-04-12 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_repuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('rosca', models.CharField(blank=True, max_length=50, null=True)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('und', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_necesaria', models.IntegerField()),
                ('existencia_stock', models.IntegerField()),
                ('salida', models.IntegerField()),
                ('partes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_repuesto.partes')),
            ],
        ),
        migrations.RemoveField(
            model_name='existencia_stock',
            name='partes',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='partes',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='partes',
        ),
        migrations.DeleteModel(
            name='Cantidad_necesaria',
        ),
        migrations.DeleteModel(
            name='Existencia_stock',
        ),
        migrations.DeleteModel(
            name='Medida',
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
