# Generated by Django 4.2.7 on 2024-04-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_repuesto', '0002_inventario_remove_existencia_stock_partes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partes',
            new_name='Parte',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='partes',
            new_name='parte',
        ),
    ]
