# Generated by Django 4.2.7 on 2024-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_repuesto', '0003_rename_partes_parte_rename_partes_inventario_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='image',
            field=models.ImageField(default=None, upload_to='repuesto/image'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='largo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='rosca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='und',
            field=models.CharField(default='', max_length=50),
        ),
    ]
