# Generated by Django 4.2.7 on 2024-03-27 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_herramienta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='costo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='descripción',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='encargado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='estado_de_la_herramienta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='fecha_de_adquisición',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='teléfono_encargado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='ubicación',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mantenimientoherramienta',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 21, 58, 388193)),
        ),
    ]
