# Generated by Django 4.2.7 on 2024-04-01 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_herramienta', '0003_alter_mantenimientoherramienta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoherramienta',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 53, 21, 708494)),
        ),
    ]
