# Generated by Django 4.2.7 on 2024-04-11 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_herramienta', '0006_alter_herramienta_intervalo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoherramienta',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 44, 12, 644316)),
        ),
    ]
