# Generated by Django 4.2.7 on 2024-06-06 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('teléfono_encargado', models.CharField(max_length=100)),
                ('descripción', models.TextField(max_length=500)),
                ('ubicación', models.CharField(max_length=100)),
                ('capacidad', models.CharField(max_length=100)),
                ('tipo_de_área', models.CharField(max_length=100)),
                ('estado_de_ocupación', models.CharField(max_length=100)),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('intervalo_mantenimiento', models.IntegerField()),
                ('image', models.ImageField(upload_to='area/image')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimientoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.time(13, 40, 53, 781621))),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time(13, 40, 53, 781669))),
                ('operador', models.CharField(default='', max_length=100)),
                ('descripción', models.TextField(default='', max_length=500)),
                ('image_antes', models.ImageField(default=None, upload_to='area/mantenimiento/antes')),
                ('image', models.ImageField(default=None, upload_to='area/mantenimiento/despues')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_area.area')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_area.tipomantenimientoarea')),
            ],
        ),
    ]
