# Generated by Django 4.2.7 on 2023-12-17 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 13, 58, 719472)),
        ),
    ]
