# Generated by Django 4.2.7 on 2023-12-17 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0002_alter_mantenimientoarea_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='area/image'),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 16, 10, 257696)),
        ),
    ]
