# Generated by Django 4.2.7 on 2024-03-26 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0004_alter_area_image_alter_area_intervalo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 58, 14, 617530)),
        ),
    ]
