# Generated by Django 4.2.7 on 2024-03-27 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0005_alter_mantenimientoarea_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='capacidad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='descripción',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='area',
            name='estado_de_ocupación',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='tipo_de_área',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='ubicación',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(14, 21, 58, 382431)),
        ),
    ]
