# Generated by Django 4.2.7 on 2024-04-01 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0006_alter_area_capacidad_alter_area_descripción_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='capacidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 42, 24, 588849)),
        ),
    ]
