# Generated by Django 4.2.7 on 2024-04-01 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0007_alter_area_capacidad_alter_mantenimientoarea_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 53, 21, 700506)),
        ),
    ]
