# Generated by Django 4.2.7 on 2024-04-09 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0008_alter_mantenimientoarea_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 16, 49, 270941)),
        ),
    ]
