# Generated by Django 4.2.7 on 2024-04-11 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0009_alter_mantenimientoarea_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(1, 22, 44, 101316)),
        ),
    ]
