# Generated by Django 4.2.7 on 2024-04-11 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0010_alter_mantenimientoarea_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoarea',
            name='descripción',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mantenimientoarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mantenimientoarea',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(18, 44, 12, 633467)),
        ),
        migrations.AddField(
            model_name='mantenimientoarea',
            name='image',
            field=models.ImageField(default=None, upload_to='area/mantenimiento/despues'),
        ),
        migrations.AddField(
            model_name='mantenimientoarea',
            name='image_antes',
            field=models.ImageField(default=None, upload_to='area/mantenimiento/antes'),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 44, 12, 633548)),
        ),
    ]
