# Generated by Django 4.2.7 on 2024-04-12 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0012_alter_mantenimientoarea_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(23, 7, 52, 925973)),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(23, 7, 52, 925918)),
        ),
    ]
