# Generated by Django 4.2.7 on 2024-04-15 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_area', '0015_alter_mantenimientoarea_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 18, 44, 83118)),
        ),
        migrations.AlterField(
            model_name='mantenimientoarea',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(13, 18, 44, 83080)),
        ),
    ]
