# Generated by Django 4.2.7 on 2024-04-01 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripción', models.TextField(max_length=500)),
                ('número_de_serie_o_modelo', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('costo_de_adquisición', models.IntegerField()),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('intervalo_mantenimiento', models.IntegerField()),
                ('image', models.ImageField(upload_to='componente/image')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_maquina.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimientoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='hora',
            field=models.TimeField(default=datetime.time(21, 53, 21, 712369)),
        ),
        migrations.CreateModel(
            name='MantenimientoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default=datetime.time(21, 53, 21, 715758))),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_maquina.componente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGE_maquina.tipomantenimientocomponente')),
            ],
        ),
    ]
