# Generated by Django 4.2.7 on 2024-04-09 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGE_maquina', '0003_remove_mantenimientocomponente_componente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientomaquina',
            name='hr_maquina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 16, 49, 281957)),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(12, 16, 49, 281921)),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='image',
            field=models.ImageField(default=None, upload_to='maquina/mantenimiento/image'),
        ),
    ]
